apiVersion: batch/v1
kind: Job
metadata:
  name: zoneapi-migration-latest
  labels:
    app.kubernetes.io/name: zoneapi
    app.kubernetes.io/instance: zoneapi
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: migration
    app.kubernetes.io/part-of: zoneapi
    app.kubernetes.io/managed-by: manual
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 1200  # 20 minutes timeout
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zoneapi
        app.kubernetes.io/instance: zoneapi
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      securityContext:
        fsGroup: 10001
      containers:
        - name: migration
          image: "ACR_REGISTRY_PLACEHOLDER/zoneapi:latest"  # Will be replaced by CI/CD
          imagePullPolicy: IfNotPresent
          workingDir: /app
          command: ["./efbundle"]
          args: 
            - "--connection"
            - "Host=DB_HOST_PLACEHOLDER;Port=5432;Database=zone;Username=postgres;Password=$DB_PASSWORD;CommandTimeout=300;Timeout=60;"
            - "--verbose"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Kubernetes"
            - name: DOTNET_BUNDLE_EXTRACT_BASE_DIR
              value: "/tmp"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zoneapi-db-secret
                  key: password
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: tmp
          emptyDir: {} 