{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "zoneapi.fullname" . }}-migration-{{ .Values.image.tag | default .Chart.AppVersion | replace "." "-" | replace ":" "-" }}
  labels:
    {{- include "zoneapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  # Using standalone job approach - no pre-install hooks
spec:
  backoffLimit: {{ .Values.migration.backoffLimit | default 3 }}
  activeDeadlineSeconds: {{ .Values.migration.timeout | default 600 }}
  template:
    metadata:
      labels:
        {{- include "zoneapi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      securityContext:
        fsGroup: 10001  # Match Dockerfile user setup
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app  # Set working directory to where efbundle is located
          command: ["./efbundle"]  # Run efbundle from /app directory
          args: 
            - "--connection"
            - "Host={{ .Values.database.host }};Port={{ .Values.database.port }};Database={{ .Values.database.name }};Username={{ .Values.database.user }};Password=$DB_PASSWORD;CommandTimeout=300;Timeout=60;"
            - "--verbose"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environment | quote }}
            - name: DOTNET_BUNDLE_EXTRACT_BASE_DIR
              value: "/tmp"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "zoneapi.fullname" . }}-db-secret
                  key: password
          securityContext:
            runAsUser: 0  # Run as root for migration bundle execution
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"  # Increased for migration operations
              cpu: "500m"      # Increased for migration operations
      volumes:
        - name: tmp
          emptyDir: {}
{{- end }} 