# Default values for zoneapi
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: ""  # Will be overridden by CI/CD
  pullPolicy: IfNotPresent
  tag: ""  # Will be overridden by CI/CD

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 10001  # Match Dockerfile user

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false  # Allow writes to /tmp for migrations
  runAsNonRoot: true
  runAsUser: 10001  # Match Dockerfile UID

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: zoneapi.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: zoneapi-tls
      hosts:
        - zoneapi.local

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Database configuration
database:
  host: ""  # Will be set by CI/CD
  port: 5432
  name: "zone"
  user: "postgres"
  password: ""  # Will be set by CI/CD via secret

# Health check configuration - Optimized based on actual performance
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 15  # App starts quickly with correct config
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

# Liveness probe (when to restart container) - Optimized for quick startup
livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 30  # Reduced since app starts in ~10 seconds
  periodSeconds: 30
  timeoutSeconds: 15  # Reasonable timeout for health checks
  failureThreshold: 3  # Standard failure threshold
  successThreshold: 1

# Readiness probe (when to start receiving traffic) - Optimized startup
readinessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 20  # Allow startup and DB connection
  periodSeconds: 10
  timeoutSeconds: 10  # Faster timeout for readiness
  failureThreshold: 3  # Standard failure threshold
  successThreshold: 1

# Deployment strategy
deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0  # Keep at least one pod running

# Restart policy
restartPolicy: Always
terminationGracePeriodSeconds: 10  # Faster shutdown

# Environment configuration
environment: "Development"

# Debug configuration
debug:
  enabled: true

# Migration configuration - Updated for efbundle approach
migration:
  enabled: true  # Using standalone migration job with efbundle
  timeout: 600  # 10 minutes for Azure PostgreSQL
  backoffLimit: 3  # Max 3 retries
  activeDeadlineSeconds: 600  # Kill job after 10 minutes total
  bundlePath: "/app/efbundle"  # Path to migration bundle in container

# Monitoring and observability
monitoring:
  enabled: true
  serviceMonitor:
    enabled: false
    namespace: monitoring
    interval: 30s 